name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package -DskipTests -Dmaven.test.skip=true
      env:
        MAVEN_OPTS: -Dmaven.repo.local=${{ github.workspace }}/.m2/repository

    - name: Exclude /bin directory
      run: rm -rf bin